version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U weather_user -d weather_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - OPENWEATHER_API_KEY=d5b9892542a831a20e5cde81df11674e
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=weather_db
      - DB_USER=weather_user
      - DB_PASSWORD=weather_pass
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
